base_info:
  title: Since 1980s # Site title
  author: Joseph Lee # Author name
  url: https://blog.iiba.fun # Site url

style:
  # Theme primary color
  primary_color: "#005080"

  # Avatar (You can use local image or image external link)
  avatar: /images/avatar.svg # avatar of the author

  # Favicon (You can use local image or image external link)
  favicon: # favicon of the site

  # Article image align position
  article_img_align: center # value: left | center

  # Left side width
  left_side_width: 240px #sidebar width, for toc

  # Content area max width
  content_max_width: 960px #content max width, for article

  # 导航栏的渐变背景设置。
  nav_color:
    left: "#f78736" #left side
    right: "#367df7" #right side
    transparency: 35 #percent (10-99)

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: false # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_img: /images/wallheaven-bg.webp # background image of the first screen, use relative path or external link
    description: 肉体包裹的心灵，也是经不起炎凉，受不得磕碰的。 # the title in the middle of the first screen

  # Scroll style settings
  scroll:
    progress_bar: # reading progress bar
      enable: true
    percent: # reading progress percent
      enable: false

social_contact: # social contact icons in the first screen, you can add more by using fontawesome icon names
  enable: true
  links:
    github: https://github.com/limeng0403 # your GitHub URL
    # instagram: # your Instagram URL
    # zhihu: # your ZhiHu URL
    # twitter: # your twitter URL
    email: lionft@qq.com # your email

home_article:
  category:
    enable: true # show category in home page article block
    limit: 3 # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 5 # max number of tags shown in home page article block

post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: true
    wordcount: true # word count, one article
    min2read: true # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: true # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    # custom_label_list: ["Trainee", "Engineer", "Architect", "CTO", "BOSS"]

code_copy:
  enable: true
  style: mac # values: default | mac

